var annotated_dup =
[
    [ "RoboClerk", "namespaceRoboClerk.html", [
      [ "AISystem", "namespaceRoboClerk_1_1AISystem.html", [
        [ "AISystemPluginBase", "classRoboClerk_1_1AISystem_1_1AISystemPluginBase.html", "classRoboClerk_1_1AISystem_1_1AISystemPluginBase" ],
        [ "IAISystemPlugin", "interfaceRoboClerk_1_1AISystem_1_1IAISystemPlugin.html", "interfaceRoboClerk_1_1AISystem_1_1IAISystemPlugin" ],
        [ "PromptTemplate", "classRoboClerk_1_1AISystem_1_1PromptTemplate.html", "classRoboClerk_1_1AISystem_1_1PromptTemplate" ]
      ] ],
      [ "AnnotatedUnitTests", "namespaceRoboClerk_1_1AnnotatedUnitTests.html", [
        [ "AnnotatedUnitTestsPlugin", "classRoboClerk_1_1AnnotatedUnitTests_1_1AnnotatedUnitTestsPlugin.html", "classRoboClerk_1_1AnnotatedUnitTests_1_1AnnotatedUnitTestsPlugin" ]
      ] ],
      [ "AzureDevOps", "namespaceRoboClerk_1_1AzureDevOps.html", [
        [ "AzureDevOpsSLMSPlugin", "classRoboClerk_1_1AzureDevOps_1_1AzureDevOpsSLMSPlugin.html", "classRoboClerk_1_1AzureDevOps_1_1AzureDevOpsSLMSPlugin" ],
        [ "HtmlToTextConverter", "classRoboClerk_1_1AzureDevOps_1_1HtmlToTextConverter.html", null ]
      ] ],
      [ "Configuration", "namespaceRoboClerk_1_1Configuration.html", [
        [ "CheckpointConfig", "classRoboClerk_1_1Configuration_1_1CheckpointConfig.html", "classRoboClerk_1_1Configuration_1_1CheckpointConfig" ],
        [ "Configuration", "classRoboClerk_1_1Configuration_1_1Configuration.html", "classRoboClerk_1_1Configuration_1_1Configuration" ],
        [ "ConfigurationValues", "classRoboClerk_1_1Configuration_1_1ConfigurationValues.html", "classRoboClerk_1_1Configuration_1_1ConfigurationValues" ],
        [ "DocumentConfig", "classRoboClerk_1_1Configuration_1_1DocumentConfig.html", "classRoboClerk_1_1Configuration_1_1DocumentConfig" ],
        [ "IConfiguration", "interfaceRoboClerk_1_1Configuration_1_1IConfiguration.html", "interfaceRoboClerk_1_1Configuration_1_1IConfiguration" ],
        [ "TraceConfig", "classRoboClerk_1_1Configuration_1_1TraceConfig.html", "classRoboClerk_1_1Configuration_1_1TraceConfig" ],
        [ "TraceConfigElement", "classRoboClerk_1_1Configuration_1_1TraceConfigElement.html", "classRoboClerk_1_1Configuration_1_1TraceConfigElement" ],
        [ "TruthItemConfig", "classRoboClerk_1_1Configuration_1_1TruthItemConfig.html", "classRoboClerk_1_1Configuration_1_1TruthItemConfig" ]
      ] ],
      [ "ContentCreators", "namespaceRoboClerk_1_1ContentCreators.html", [
        [ "AIContentCreator", "classRoboClerk_1_1ContentCreators_1_1AIContentCreator.html", "classRoboClerk_1_1ContentCreators_1_1AIContentCreator" ],
        [ "Anomaly", "classRoboClerk_1_1ContentCreators_1_1Anomaly.html", "classRoboClerk_1_1ContentCreators_1_1Anomaly" ],
        [ "ContentCreatorBase", "classRoboClerk_1_1ContentCreators_1_1ContentCreatorBase.html", "classRoboClerk_1_1ContentCreators_1_1ContentCreatorBase" ],
        [ "Document", "classRoboClerk_1_1ContentCreators_1_1Document.html", "classRoboClerk_1_1ContentCreators_1_1Document" ],
        [ "DocumentationRequirement", "classRoboClerk_1_1ContentCreators_1_1DocumentationRequirement.html", "classRoboClerk_1_1ContentCreators_1_1DocumentationRequirement" ],
        [ "ExcelTable", "classRoboClerk_1_1ContentCreators_1_1ExcelTable.html", "classRoboClerk_1_1ContentCreators_1_1ExcelTable" ],
        [ "IContentCreator", "interfaceRoboClerk_1_1ContentCreators_1_1IContentCreator.html", "interfaceRoboClerk_1_1ContentCreators_1_1IContentCreator" ],
        [ "MultiItemContentCreator", "classRoboClerk_1_1ContentCreators_1_1MultiItemContentCreator.html", "classRoboClerk_1_1ContentCreators_1_1MultiItemContentCreator" ],
        [ "RequirementBase", "classRoboClerk_1_1ContentCreators_1_1RequirementBase.html", "classRoboClerk_1_1ContentCreators_1_1RequirementBase" ],
        [ "Risk", "classRoboClerk_1_1ContentCreators_1_1Risk.html", "classRoboClerk_1_1ContentCreators_1_1Risk" ],
        [ "RiskTraceabilityMatrix", "classRoboClerk_1_1ContentCreators_1_1RiskTraceabilityMatrix.html", "classRoboClerk_1_1ContentCreators_1_1RiskTraceabilityMatrix" ],
        [ "SoftwareLevelTraceabilityMatrix", "classRoboClerk_1_1ContentCreators_1_1SoftwareLevelTraceabilityMatrix.html", "classRoboClerk_1_1ContentCreators_1_1SoftwareLevelTraceabilityMatrix" ],
        [ "SoftwareRequirement", "classRoboClerk_1_1ContentCreators_1_1SoftwareRequirement.html", "classRoboClerk_1_1ContentCreators_1_1SoftwareRequirement" ],
        [ "SoftwareSystemTest", "classRoboClerk_1_1ContentCreators_1_1SoftwareSystemTest.html", "classRoboClerk_1_1ContentCreators_1_1SoftwareSystemTest" ],
        [ "SOUP", "classRoboClerk_1_1ContentCreators_1_1SOUP.html", "classRoboClerk_1_1ContentCreators_1_1SOUP" ],
        [ "SystemLevelTraceabilityMatrix", "classRoboClerk_1_1ContentCreators_1_1SystemLevelTraceabilityMatrix.html", "classRoboClerk_1_1ContentCreators_1_1SystemLevelTraceabilityMatrix" ],
        [ "SystemRequirement", "classRoboClerk_1_1ContentCreators_1_1SystemRequirement.html", "classRoboClerk_1_1ContentCreators_1_1SystemRequirement" ],
        [ "TemplateSection", "classRoboClerk_1_1ContentCreators_1_1TemplateSection.html", "classRoboClerk_1_1ContentCreators_1_1TemplateSection" ],
        [ "Trace", "classRoboClerk_1_1ContentCreators_1_1Trace.html", "classRoboClerk_1_1ContentCreators_1_1Trace" ],
        [ "TraceabilityMatrixBase", "classRoboClerk_1_1ContentCreators_1_1TraceabilityMatrixBase.html", "classRoboClerk_1_1ContentCreators_1_1TraceabilityMatrixBase" ],
        [ "TraceMatrix", "classRoboClerk_1_1ContentCreators_1_1TraceMatrix.html", "classRoboClerk_1_1ContentCreators_1_1TraceMatrix" ],
        [ "UnitTest", "classRoboClerk_1_1ContentCreators_1_1UnitTest.html", "classRoboClerk_1_1ContentCreators_1_1UnitTest" ]
      ] ],
      [ "DependenciesFile", "namespaceRoboClerk_1_1DependenciesFile.html", [
        [ "DependenciesFilePlugin", "classRoboClerk_1_1DependenciesFile_1_1DependenciesFilePlugin.html", "classRoboClerk_1_1DependenciesFile_1_1DependenciesFilePlugin" ]
      ] ],
      [ "Redmine", "namespaceRoboClerk_1_1Redmine.html", [
        [ "AssignedTo", "classRoboClerk_1_1Redmine_1_1AssignedTo.html", "classRoboClerk_1_1Redmine_1_1AssignedTo" ],
        [ "Author", "classRoboClerk_1_1Redmine_1_1Author.html", "classRoboClerk_1_1Redmine_1_1Author" ],
        [ "CustomField", "classRoboClerk_1_1Redmine_1_1CustomField.html", "classRoboClerk_1_1Redmine_1_1CustomField" ],
        [ "DefaultStatus", "classRoboClerk_1_1Redmine_1_1DefaultStatus.html", "classRoboClerk_1_1Redmine_1_1DefaultStatus" ],
        [ "FixedVersion", "classRoboClerk_1_1Redmine_1_1FixedVersion.html", "classRoboClerk_1_1Redmine_1_1FixedVersion" ],
        [ "Parent", "classRoboClerk_1_1Redmine_1_1Parent.html", "classRoboClerk_1_1Redmine_1_1Parent" ],
        [ "Priority", "classRoboClerk_1_1Redmine_1_1Priority.html", "classRoboClerk_1_1Redmine_1_1Priority" ],
        [ "RedmineIssue", "classRoboClerk_1_1Redmine_1_1RedmineIssue.html", "classRoboClerk_1_1Redmine_1_1RedmineIssue" ],
        [ "RedmineIssues", "classRoboClerk_1_1Redmine_1_1RedmineIssues.html", "classRoboClerk_1_1Redmine_1_1RedmineIssues" ],
        [ "RedmineProject", "classRoboClerk_1_1Redmine_1_1RedmineProject.html", "classRoboClerk_1_1Redmine_1_1RedmineProject" ],
        [ "RedmineProjects", "classRoboClerk_1_1Redmine_1_1RedmineProjects.html", "classRoboClerk_1_1Redmine_1_1RedmineProjects" ],
        [ "RedmineSLMSPlugin", "classRoboClerk_1_1Redmine_1_1RedmineSLMSPlugin.html", "classRoboClerk_1_1Redmine_1_1RedmineSLMSPlugin" ],
        [ "RedmineTracker", "classRoboClerk_1_1Redmine_1_1RedmineTracker.html", "classRoboClerk_1_1Redmine_1_1RedmineTracker" ],
        [ "RedmineTrackers", "classRoboClerk_1_1Redmine_1_1RedmineTrackers.html", "classRoboClerk_1_1Redmine_1_1RedmineTrackers" ],
        [ "Relation", "classRoboClerk_1_1Redmine_1_1Relation.html", "classRoboClerk_1_1Redmine_1_1Relation" ],
        [ "Status", "classRoboClerk_1_1Redmine_1_1Status.html", "classRoboClerk_1_1Redmine_1_1Status" ]
      ] ],
      [ "AnomalyItem", "classRoboClerk_1_1AnomalyItem.html", "classRoboClerk_1_1AnomalyItem" ],
      [ "CheckpointDataSources", "classRoboClerk_1_1CheckpointDataSources.html", "classRoboClerk_1_1CheckpointDataSources" ],
      [ "CheckpointDataStorage", "classRoboClerk_1_1CheckpointDataStorage.html", "classRoboClerk_1_1CheckpointDataStorage" ],
      [ "Commands", "classRoboClerk_1_1Commands.html", "classRoboClerk_1_1Commands" ],
      [ "DataSourcePluginBase", "classRoboClerk_1_1DataSourcePluginBase.html", "classRoboClerk_1_1DataSourcePluginBase" ],
      [ "DataSourcesBase", "classRoboClerk_1_1DataSourcesBase.html", "classRoboClerk_1_1DataSourcesBase" ],
      [ "DocContentItem", "classRoboClerk_1_1DocContentItem.html", "classRoboClerk_1_1DocContentItem" ],
      [ "Document", "classRoboClerk_1_1Document.html", "classRoboClerk_1_1Document" ],
      [ "ExternalDependency", "classRoboClerk_1_1ExternalDependency.html", "classRoboClerk_1_1ExternalDependency" ],
      [ "GitRepository", "classRoboClerk_1_1GitRepository.html", "classRoboClerk_1_1GitRepository" ],
      [ "IDataSourcePlugin", "interfaceRoboClerk_1_1IDataSourcePlugin.html", "interfaceRoboClerk_1_1IDataSourcePlugin" ],
      [ "IDataSources", "interfaceRoboClerk_1_1IDataSources.html", "interfaceRoboClerk_1_1IDataSources" ],
      [ "IPlugin", "interfaceRoboClerk_1_1IPlugin.html", "interfaceRoboClerk_1_1IPlugin" ],
      [ "IPluginLoader", "interfaceRoboClerk_1_1IPluginLoader.html", "interfaceRoboClerk_1_1IPluginLoader" ],
      [ "Item", "classRoboClerk_1_1Item.html", "classRoboClerk_1_1Item" ],
      [ "ItemLink", "classRoboClerk_1_1ItemLink.html", "classRoboClerk_1_1ItemLink" ],
      [ "ItemTemplateRenderer", "classRoboClerk_1_1ItemTemplateRenderer.html", "classRoboClerk_1_1ItemTemplateRenderer" ],
      [ "ITraceabilityAnalysis", "interfaceRoboClerk_1_1ITraceabilityAnalysis.html", "interfaceRoboClerk_1_1ITraceabilityAnalysis" ],
      [ "LinkedItem", "classRoboClerk_1_1LinkedItem.html", "classRoboClerk_1_1LinkedItem" ],
      [ "PlaceholderItem", "classRoboClerk_1_1PlaceholderItem.html", "classRoboClerk_1_1PlaceholderItem" ],
      [ "PluginBase", "classRoboClerk_1_1PluginBase.html", "classRoboClerk_1_1PluginBase" ],
      [ "PluginDataSources", "classRoboClerk_1_1PluginDataSources.html", "classRoboClerk_1_1PluginDataSources" ],
      [ "PluginLoadContext", "classRoboClerk_1_1PluginLoadContext.html", "classRoboClerk_1_1PluginLoadContext" ],
      [ "PluginLoader", "classRoboClerk_1_1PluginLoader.html", "classRoboClerk_1_1PluginLoader" ],
      [ "Program", "classRoboClerk_1_1Program.html", null ],
      [ "RequirementItem", "classRoboClerk_1_1RequirementItem.html", "classRoboClerk_1_1RequirementItem" ],
      [ "RiskItem", "classRoboClerk_1_1RiskItem.html", "classRoboClerk_1_1RiskItem" ],
      [ "RoboClerkCore", "classRoboClerk_1_1RoboClerkCore.html", "classRoboClerk_1_1RoboClerkCore" ],
      [ "RoboClerkOrderedDictionary", "classRoboClerk_1_1RoboClerkOrderedDictionary.html", "classRoboClerk_1_1RoboClerkOrderedDictionary" ],
      [ "RoboClerkTag", "classRoboClerk_1_1RoboClerkTag.html", "classRoboClerk_1_1RoboClerkTag" ],
      [ "ScriptingBridge", "classRoboClerk_1_1ScriptingBridge.html", "classRoboClerk_1_1ScriptingBridge" ],
      [ "SLMSPluginBase", "classRoboClerk_1_1SLMSPluginBase.html", "classRoboClerk_1_1SLMSPluginBase" ],
      [ "SoftwareSystemTestItem", "classRoboClerk_1_1SoftwareSystemTestItem.html", "classRoboClerk_1_1SoftwareSystemTestItem" ],
      [ "SOUPItem", "classRoboClerk_1_1SOUPItem.html", "classRoboClerk_1_1SOUPItem" ],
      [ "SourceCodeAnalysisPluginBase", "classRoboClerk_1_1SourceCodeAnalysisPluginBase.html", "classRoboClerk_1_1SourceCodeAnalysisPluginBase" ],
      [ "TagInvalidException", "classRoboClerk_1_1TagInvalidException.html", "classRoboClerk_1_1TagInvalidException" ],
      [ "TestStep", "classRoboClerk_1_1TestStep.html", "classRoboClerk_1_1TestStep" ],
      [ "TraceabilityAnalysis", "classRoboClerk_1_1TraceabilityAnalysis.html", "classRoboClerk_1_1TraceabilityAnalysis" ],
      [ "TraceBase", "classRoboClerk_1_1TraceBase.html", "classRoboClerk_1_1TraceBase" ],
      [ "TraceEntity", "classRoboClerk_1_1TraceEntity.html", "classRoboClerk_1_1TraceEntity" ],
      [ "TraceIssue", "classRoboClerk_1_1TraceIssue.html", "classRoboClerk_1_1TraceIssue" ],
      [ "TraceLink", "classRoboClerk_1_1TraceLink.html", "classRoboClerk_1_1TraceLink" ],
      [ "TraceSpecification", "classRoboClerk_1_1TraceSpecification.html", "classRoboClerk_1_1TraceSpecification" ],
      [ "UnitTestAttribute", "classRoboClerk_1_1UnitTestAttribute.html", "classRoboClerk_1_1UnitTestAttribute" ],
      [ "UnitTestFNPlugin", "classRoboClerk_1_1UnitTestFNPlugin.html", "classRoboClerk_1_1UnitTestFNPlugin" ],
      [ "UnitTestItem", "classRoboClerk_1_1UnitTestItem.html", "classRoboClerk_1_1UnitTestItem" ]
    ] ]
];