var annotated_dup =
[
    [ "RoboClerk", "namespace_robo_clerk.html", [
      [ "AnnotatedUnitTests", "namespace_robo_clerk_1_1_annotated_unit_tests.html", [
        [ "AnnotatedUnitTestsPlugin", "class_robo_clerk_1_1_annotated_unit_tests_1_1_annotated_unit_tests_plugin.html", "class_robo_clerk_1_1_annotated_unit_tests_1_1_annotated_unit_tests_plugin" ]
      ] ],
      [ "AzureDevOps", "namespace_robo_clerk_1_1_azure_dev_ops.html", [
        [ "AzureDevOpsSLMSPlugin", "class_robo_clerk_1_1_azure_dev_ops_1_1_azure_dev_ops_s_l_m_s_plugin.html", "class_robo_clerk_1_1_azure_dev_ops_1_1_azure_dev_ops_s_l_m_s_plugin" ],
        [ "HtmlToTextConverter", "class_robo_clerk_1_1_azure_dev_ops_1_1_html_to_text_converter.html", null ]
      ] ],
      [ "Configuration", "namespace_robo_clerk_1_1_configuration.html", [
        [ "CheckpointConfig", "class_robo_clerk_1_1_configuration_1_1_checkpoint_config.html", "class_robo_clerk_1_1_configuration_1_1_checkpoint_config" ],
        [ "Configuration", "class_robo_clerk_1_1_configuration_1_1_configuration.html", "class_robo_clerk_1_1_configuration_1_1_configuration" ],
        [ "ConfigurationValues", "class_robo_clerk_1_1_configuration_1_1_configuration_values.html", "class_robo_clerk_1_1_configuration_1_1_configuration_values" ],
        [ "DocumentConfig", "class_robo_clerk_1_1_configuration_1_1_document_config.html", "class_robo_clerk_1_1_configuration_1_1_document_config" ],
        [ "IConfiguration", "interface_robo_clerk_1_1_configuration_1_1_i_configuration.html", "interface_robo_clerk_1_1_configuration_1_1_i_configuration" ],
        [ "TraceConfig", "class_robo_clerk_1_1_configuration_1_1_trace_config.html", "class_robo_clerk_1_1_configuration_1_1_trace_config" ],
        [ "TraceConfigElement", "class_robo_clerk_1_1_configuration_1_1_trace_config_element.html", "class_robo_clerk_1_1_configuration_1_1_trace_config_element" ]
      ] ],
      [ "ContentCreators", "namespace_robo_clerk_1_1_content_creators.html", [
        [ "Anomaly", "class_robo_clerk_1_1_content_creators_1_1_anomaly.html", "class_robo_clerk_1_1_content_creators_1_1_anomaly" ],
        [ "ContentCreatorBase", "class_robo_clerk_1_1_content_creators_1_1_content_creator_base.html", "class_robo_clerk_1_1_content_creators_1_1_content_creator_base" ],
        [ "DocumentationRequirement", "class_robo_clerk_1_1_content_creators_1_1_documentation_requirement.html", "class_robo_clerk_1_1_content_creators_1_1_documentation_requirement" ],
        [ "ExcelTable", "class_robo_clerk_1_1_content_creators_1_1_excel_table.html", "class_robo_clerk_1_1_content_creators_1_1_excel_table" ],
        [ "IContentCreator", "interface_robo_clerk_1_1_content_creators_1_1_i_content_creator.html", "interface_robo_clerk_1_1_content_creators_1_1_i_content_creator" ],
        [ "MultiItemContentCreator", "class_robo_clerk_1_1_content_creators_1_1_multi_item_content_creator.html", "class_robo_clerk_1_1_content_creators_1_1_multi_item_content_creator" ],
        [ "RequirementBase", "class_robo_clerk_1_1_content_creators_1_1_requirement_base.html", "class_robo_clerk_1_1_content_creators_1_1_requirement_base" ],
        [ "Risk", "class_robo_clerk_1_1_content_creators_1_1_risk.html", "class_robo_clerk_1_1_content_creators_1_1_risk" ],
        [ "RiskTable", "class_robo_clerk_1_1_content_creators_1_1_risk_table.html", "class_robo_clerk_1_1_content_creators_1_1_risk_table" ],
        [ "RiskTraceabilityMatrix", "class_robo_clerk_1_1_content_creators_1_1_risk_traceability_matrix.html", "class_robo_clerk_1_1_content_creators_1_1_risk_traceability_matrix" ],
        [ "SoftwareLevelTraceabilityMatrix", "class_robo_clerk_1_1_content_creators_1_1_software_level_traceability_matrix.html", "class_robo_clerk_1_1_content_creators_1_1_software_level_traceability_matrix" ],
        [ "SoftwareRequirement", "class_robo_clerk_1_1_content_creators_1_1_software_requirement.html", "class_robo_clerk_1_1_content_creators_1_1_software_requirement" ],
        [ "SoftwareSystemTest", "class_robo_clerk_1_1_content_creators_1_1_software_system_test.html", "class_robo_clerk_1_1_content_creators_1_1_software_system_test" ],
        [ "SOUP", "class_robo_clerk_1_1_content_creators_1_1_s_o_u_p.html", "class_robo_clerk_1_1_content_creators_1_1_s_o_u_p" ],
        [ "SystemLevelTraceabilityMatrix", "class_robo_clerk_1_1_content_creators_1_1_system_level_traceability_matrix.html", "class_robo_clerk_1_1_content_creators_1_1_system_level_traceability_matrix" ],
        [ "SystemRequirement", "class_robo_clerk_1_1_content_creators_1_1_system_requirement.html", "class_robo_clerk_1_1_content_creators_1_1_system_requirement" ],
        [ "TemplateSection", "class_robo_clerk_1_1_content_creators_1_1_template_section.html", "class_robo_clerk_1_1_content_creators_1_1_template_section" ],
        [ "Trace", "class_robo_clerk_1_1_content_creators_1_1_trace.html", "class_robo_clerk_1_1_content_creators_1_1_trace" ],
        [ "TraceMatrix", "class_robo_clerk_1_1_content_creators_1_1_trace_matrix.html", "class_robo_clerk_1_1_content_creators_1_1_trace_matrix" ],
        [ "UnitTest", "class_robo_clerk_1_1_content_creators_1_1_unit_test.html", "class_robo_clerk_1_1_content_creators_1_1_unit_test" ]
      ] ],
      [ "DependenciesFile", "namespace_robo_clerk_1_1_dependencies_file.html", [
        [ "DependenciesFilePlugin", "class_robo_clerk_1_1_dependencies_file_1_1_dependencies_file_plugin.html", "class_robo_clerk_1_1_dependencies_file_1_1_dependencies_file_plugin" ]
      ] ],
      [ "Redmine", "namespace_robo_clerk_1_1_redmine.html", [
        [ "AssignedTo", "class_robo_clerk_1_1_redmine_1_1_assigned_to.html", "class_robo_clerk_1_1_redmine_1_1_assigned_to" ],
        [ "Author", "class_robo_clerk_1_1_redmine_1_1_author.html", "class_robo_clerk_1_1_redmine_1_1_author" ],
        [ "CustomField", "class_robo_clerk_1_1_redmine_1_1_custom_field.html", "class_robo_clerk_1_1_redmine_1_1_custom_field" ],
        [ "DefaultStatus", "class_robo_clerk_1_1_redmine_1_1_default_status.html", "class_robo_clerk_1_1_redmine_1_1_default_status" ],
        [ "FixedVersion", "class_robo_clerk_1_1_redmine_1_1_fixed_version.html", "class_robo_clerk_1_1_redmine_1_1_fixed_version" ],
        [ "Parent", "class_robo_clerk_1_1_redmine_1_1_parent.html", "class_robo_clerk_1_1_redmine_1_1_parent" ],
        [ "Priority", "class_robo_clerk_1_1_redmine_1_1_priority.html", "class_robo_clerk_1_1_redmine_1_1_priority" ],
        [ "RedmineIssue", "class_robo_clerk_1_1_redmine_1_1_redmine_issue.html", "class_robo_clerk_1_1_redmine_1_1_redmine_issue" ],
        [ "RedmineIssues", "class_robo_clerk_1_1_redmine_1_1_redmine_issues.html", "class_robo_clerk_1_1_redmine_1_1_redmine_issues" ],
        [ "RedmineProject", "class_robo_clerk_1_1_redmine_1_1_redmine_project.html", "class_robo_clerk_1_1_redmine_1_1_redmine_project" ],
        [ "RedmineProjects", "class_robo_clerk_1_1_redmine_1_1_redmine_projects.html", "class_robo_clerk_1_1_redmine_1_1_redmine_projects" ],
        [ "RedmineSLMSPlugin", "class_robo_clerk_1_1_redmine_1_1_redmine_s_l_m_s_plugin.html", "class_robo_clerk_1_1_redmine_1_1_redmine_s_l_m_s_plugin" ],
        [ "RedmineTracker", "class_robo_clerk_1_1_redmine_1_1_redmine_tracker.html", "class_robo_clerk_1_1_redmine_1_1_redmine_tracker" ],
        [ "RedmineTrackers", "class_robo_clerk_1_1_redmine_1_1_redmine_trackers.html", "class_robo_clerk_1_1_redmine_1_1_redmine_trackers" ],
        [ "Relation", "class_robo_clerk_1_1_redmine_1_1_relation.html", "class_robo_clerk_1_1_redmine_1_1_relation" ],
        [ "Status", "class_robo_clerk_1_1_redmine_1_1_status.html", "class_robo_clerk_1_1_redmine_1_1_status" ]
      ] ],
      [ "AnomalyItem", "class_robo_clerk_1_1_anomaly_item.html", "class_robo_clerk_1_1_anomaly_item" ],
      [ "CheckpointDataSources", "class_robo_clerk_1_1_checkpoint_data_sources.html", "class_robo_clerk_1_1_checkpoint_data_sources" ],
      [ "CheckpointDataStorage", "class_robo_clerk_1_1_checkpoint_data_storage.html", "class_robo_clerk_1_1_checkpoint_data_storage" ],
      [ "Commands", "class_robo_clerk_1_1_commands.html", "class_robo_clerk_1_1_commands" ],
      [ "DataSourcesBase", "class_robo_clerk_1_1_data_sources_base.html", "class_robo_clerk_1_1_data_sources_base" ],
      [ "DocContentItem", "class_robo_clerk_1_1_doc_content_item.html", "class_robo_clerk_1_1_doc_content_item" ],
      [ "Document", "class_robo_clerk_1_1_document.html", "class_robo_clerk_1_1_document" ],
      [ "ExternalDependency", "class_robo_clerk_1_1_external_dependency.html", "class_robo_clerk_1_1_external_dependency" ],
      [ "GitRepoInformation", "class_robo_clerk_1_1_git_repo_information.html", "class_robo_clerk_1_1_git_repo_information" ],
      [ "IDataSources", "interface_robo_clerk_1_1_i_data_sources.html", "interface_robo_clerk_1_1_i_data_sources" ],
      [ "IPlugin", "interface_robo_clerk_1_1_i_plugin.html", "interface_robo_clerk_1_1_i_plugin" ],
      [ "IPluginLoader", "interface_robo_clerk_1_1_i_plugin_loader.html", "interface_robo_clerk_1_1_i_plugin_loader" ],
      [ "Item", "class_robo_clerk_1_1_item.html", "class_robo_clerk_1_1_item" ],
      [ "ItemLink", "class_robo_clerk_1_1_item_link.html", "class_robo_clerk_1_1_item_link" ],
      [ "ItemTemplateRenderer", "class_robo_clerk_1_1_item_template_renderer.html", "class_robo_clerk_1_1_item_template_renderer" ],
      [ "ITraceabilityAnalysis", "interface_robo_clerk_1_1_i_traceability_analysis.html", "interface_robo_clerk_1_1_i_traceability_analysis" ],
      [ "LinkedItem", "class_robo_clerk_1_1_linked_item.html", "class_robo_clerk_1_1_linked_item" ],
      [ "PlaceholderItem", "class_robo_clerk_1_1_placeholder_item.html", "class_robo_clerk_1_1_placeholder_item" ],
      [ "PluginBase", "class_robo_clerk_1_1_plugin_base.html", "class_robo_clerk_1_1_plugin_base" ],
      [ "PluginDataSources", "class_robo_clerk_1_1_plugin_data_sources.html", "class_robo_clerk_1_1_plugin_data_sources" ],
      [ "PluginLoadContext", "class_robo_clerk_1_1_plugin_load_context.html", "class_robo_clerk_1_1_plugin_load_context" ],
      [ "PluginLoader", "class_robo_clerk_1_1_plugin_loader.html", "class_robo_clerk_1_1_plugin_loader" ],
      [ "Program", "class_robo_clerk_1_1_program.html", null ],
      [ "RequirementItem", "class_robo_clerk_1_1_requirement_item.html", "class_robo_clerk_1_1_requirement_item" ],
      [ "RiskItem", "class_robo_clerk_1_1_risk_item.html", "class_robo_clerk_1_1_risk_item" ],
      [ "RoboClerkCore", "class_robo_clerk_1_1_robo_clerk_core.html", "class_robo_clerk_1_1_robo_clerk_core" ],
      [ "RoboClerkOrderedDictionary", "class_robo_clerk_1_1_robo_clerk_ordered_dictionary.html", "class_robo_clerk_1_1_robo_clerk_ordered_dictionary" ],
      [ "RoboClerkTag", "class_robo_clerk_1_1_robo_clerk_tag.html", "class_robo_clerk_1_1_robo_clerk_tag" ],
      [ "ScriptingBridge", "class_robo_clerk_1_1_scripting_bridge.html", "class_robo_clerk_1_1_scripting_bridge" ],
      [ "SLMSPluginBase", "class_robo_clerk_1_1_s_l_m_s_plugin_base.html", "class_robo_clerk_1_1_s_l_m_s_plugin_base" ],
      [ "SoftwareSystemTestItem", "class_robo_clerk_1_1_software_system_test_item.html", "class_robo_clerk_1_1_software_system_test_item" ],
      [ "SOUPItem", "class_robo_clerk_1_1_s_o_u_p_item.html", "class_robo_clerk_1_1_s_o_u_p_item" ],
      [ "SourceCodeAnalysisPluginBase", "class_robo_clerk_1_1_source_code_analysis_plugin_base.html", "class_robo_clerk_1_1_source_code_analysis_plugin_base" ],
      [ "TagInvalidException", "class_robo_clerk_1_1_tag_invalid_exception.html", "class_robo_clerk_1_1_tag_invalid_exception" ],
      [ "TestStep", "class_robo_clerk_1_1_test_step.html", "class_robo_clerk_1_1_test_step" ],
      [ "TraceabilityAnalysis", "class_robo_clerk_1_1_traceability_analysis.html", "class_robo_clerk_1_1_traceability_analysis" ],
      [ "TraceBase", "class_robo_clerk_1_1_trace_base.html", "class_robo_clerk_1_1_trace_base" ],
      [ "TraceEntity", "class_robo_clerk_1_1_trace_entity.html", "class_robo_clerk_1_1_trace_entity" ],
      [ "TraceIssue", "class_robo_clerk_1_1_trace_issue.html", "class_robo_clerk_1_1_trace_issue" ],
      [ "TraceLink", "class_robo_clerk_1_1_trace_link.html", "class_robo_clerk_1_1_trace_link" ],
      [ "TraceSpecification", "class_robo_clerk_1_1_trace_specification.html", "class_robo_clerk_1_1_trace_specification" ],
      [ "UnitTestAttribute", "class_robo_clerk_1_1_unit_test_attribute.html", "class_robo_clerk_1_1_unit_test_attribute" ],
      [ "UnitTestFNPlugin", "class_robo_clerk_1_1_unit_test_f_n_plugin.html", "class_robo_clerk_1_1_unit_test_f_n_plugin" ],
      [ "UnitTestItem", "class_robo_clerk_1_1_unit_test_item.html", "class_robo_clerk_1_1_unit_test_item" ]
    ] ]
];